services:
  migrator:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    image: mysql-elastic-migrator-image
    container_name: migrator_app
    depends_on:
        - mysql
    working_dir: /var/www
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: migrator_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - migrator
    depends_on:
      - migrator

  mysql:
    image: mysql:8.0
    container_name: migrator_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 33066:3306

  # elasticsearch:
  #   image: elasticsearch:9.1.4
  #   container_name: migrator_elasticsearch
  #   ports:
  #     - 9200:9200
  #   mem_limit: 1GB